ALTER TABLE "ShopSettings"
ADD COLUMN "autoSortNewCollections" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "CollectionAutoSorting"
ADD COLUMN "originalSortOrder" TEXT NOT NULL DEFAULT 'MANUAL',
ADD COLUMN "baseSortOrder" TEXT NOT NULL DEFAULT 'MANUAL',
ADD COLUMN "originalProductIds" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN "baseProductIds" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN "oosOriginalIndices" JSONB NOT NULL DEFAULT '{}',
ADD COLUMN "productCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "bulkOperationId" TEXT,
ADD COLUMN "disabledReason" TEXT,
ADD COLUMN "lastSortedAt" TIMESTAMP(3),
ADD COLUMN "lastError" TEXT,
ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
